name: Fast Deploy Next.js to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install deps
        run: npm ci --prefer-offline --no-audit

      - name: Build
        run: npm run build

      - name: Prepare standalone
        run: |
          mkdir -p .next/standalone/.next/static
          cp -r .next/static/. .next/standalone/.next/static/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2EBB9F3E6ED427AAAFF8EB60FD6F18D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A47D3F4C247B447C924B317CD6D75031 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD638EA33A474EFEAA31C9D927015A18 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: sustainability
          package: .next/standalone
          startup-command: "node server.js"
